site_name: spotPython
site_url: https://www.spotseven.de
nav:
- Home: index.md
- Download: download.md
- Examples: examples.md
- Code Reference: reference/
- About: about.md
theme:
  name: "material"
  favicon: images/favicon.png
  logo: images/spotlogo.png
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    watch:
    - src/spotPython


