site_name: spotPython
site_url: https://github.com/sequential-parameter-optimization/spotPython
repo_url: https://github.com/sequential-parameter-optimization/spotPython/tree/main
nav:
- Home: index.md
- Documentation: hyperparameter-tuning-cookbook.md
- Download: download.md
- Examples: examples.md
- Code Reference: reference/
- About: about.md
theme:
  name: material
  favicon: images/favicon.png
  logo: images/spotlogo.png
  palette:
    - primary: blue grey
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
    - search:
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - section-index
    - mkdocstrings:
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
use_directory_urls: true
watch:
- src/spotPython
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bartzbeielstein
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thomas-bartz-beielstein-3157b541/